#!/bin/bash

# Given a link to a GGUF model,
# 1. download it to the gguf/ directory,
# 2. create a .Modelfile file,
# 3. and add the model to ollama

set -e

if [ $# -ne 1 ]; then
  echo "Usage: $0 <model-link>"
  exit 1
fi

model_link="$1"

mkdir -p gguf

# expected format:
# model_link: https://huggingface.co/<ORGANIZATION>/<REPOSITORY>/resolve/main/<FILE_NAME>.gguf
# file_name: <FILE_NAME>.gguf
# modelfile_name: <FILE_NAME>.Modelfile
# repo_name: <ORGANIZATION>/<REPOSITORY>

# example expected values:
# model_link: https://huggingface.co/bartowski/Pantheon-RP-1.6.2-22b-Small-GGUF/resolve/main/Pantheon-RP-1.6.2-22b-Small-Q4_K_L.gguf
# file_name: Pantheon-RP-1.6.2-22b-Small-Q4_K_L.gguf
# modelfile_name: Pantheon-RP-1.6.2-22b-Small-Q4_K_L.Modelfile
# repo_name: bartowski/Pantheon-RP-1.6.2-22b-Small-GGUF

# ! Warning: the link may be a pointer link instead:
# Pointer Link:
# https://huggingface.co/bartowski/Pantheon-RP-1.6.2-22b-Small-GGUF/blob/main/Pantheon-RP-1.6.2-22b-Small-Q4_K_L.gguf
# Actual Model Link:
# https://huggingface.co/bartowski/Pantheon-RP-1.6.2-22b-Small-GGUF/resolve/main/Pantheon-RP-1.6.2-22b-Small-Q4_K_L.gguf
# ! if the link is a pointer link, get the actual link by replacing /blob/main/ with /resolve/main/
model_link=$(echo "$model_link" | sed 's#/blob/main/#/resolve/main/#')
file_name=$(echo "$model_link" | sed 's#.*/##')
modelfile_name=$(echo "$model_link" | sed 's#.*/##' | sed 's#.gguf#.Modelfile#')
repo_name=$(echo "$model_link" | sed -E 's#https://[^/]+/([^/]+/[^/]+)/.*#\1#')

# Store the model in the gguf/ directory

# echo "model_link: $model_link"
# echo "file_name: $file_name"
# echo "modelfile_name: $modelfile_name"
echo "repo_name: $repo_name"

# Check if the model file already exists
# Step 1. get the file name from the model link

# Step 2a. check if the file exists in the gguf/ directory
# Step 2b. if the file does not exist, download it
if [ -f "gguf/$file_name" ]; then
  echo "File already exists. Skipping download."
else
  echo "Downloading $model_link to gguf/$file_name"
  wget -P gguf "$model_link"
fi

# Create .Modelfile file
# If the model file link is:
# https://huggingface.co/bartowski/Pantheon-RP-1.6.2-22b-Small-GGUF/resolve/main/Pantheon-RP-1.6.2-22b-Small-Q4_K_L.gguf
# The .Modelfile name should be:
# Pantheon-RP-1.6.2-22b-Small-Q4_K_L.Modelfile

echo "Model file name: $modelfile_name"

cat >$modelfile_name <<EOF
# $model_link
FROM ./gguf/$file_name
EOF

# echo "Modelfile successfully created. To add this model to ollama, run the following command:"
ollama create $repo_name -f $modelfile_name
